### ISSUE TITLE
How to revert the changes?

### ISSUE THREAD

**Issue by call0fcode** [alex47/KDE-Rounded-Corners#9]
Could you please add a short explanation on the README.md about how to revert the changes? a simple command, a little script or something like this.
In my opinion it could be useful for lots of folks.

Thanks in advance and for the job you've done ;)

**Comment by gcjuan** [comment]
Ops! Sorry but I didn't realized that this is a desktop effect that can be enabled / disabled from the sistem settings like other effects.

I recomend you to append this info to the README.md because it leads  to confusion.

By the way, as additional info you can add how to remove it from the system. I made a little research (before I noticed it is a triggrerable desktop effect!!:cry:) and I removed it by running the following command on the build's directory:

`sudo xargs rm < install_manifest.txt`
